# Generated by Django 4.0.5 on 2022-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('people', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date')),
                ('body', models.TextField()),
                ('how', models.CharField(max_length=100)),
            ],
        ),
    ]
