# Generated by Django 4.1.1 on 2022-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
